import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Phu Nguyen',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: false,
    },
    {
      name: 'Apple Marketer',
      email: 'apple@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Apple Reseller',
        logo: '/images/logo1.png',
        description: 'best Apple Marketer',
        rating: 4.9,
        numReviews: 218,
      },
    },
    {
      name: 'Samsung Marketer',
      email: 'samsung@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Samsung Reseller',
        logo: '/images/logo2.png',
        description: 'best Samsung Marketer',
        rating: 4.8,
        numReviews: 127,
      },
    },
    {
      name: 'Google Marketer',
      email: 'google@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Google Reseller',
        logo: '/images/logo3.png',
        description: 'best Google Marketer',
        rating: 5.0,
        numReviews: 318,
      },
    },
    {
      name: 'Pearson Marketer',
      email: 'pearson@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Pearson Reseller',
        logo: '/images/logo4.png',
        description: 'best Pearson Marketer',
        rating: 4.5,
        numReviews: 79,
      },
    },
    {
      name: 'Oreilly Marketer',
      email: 'oreilly@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Oreilly Reseller',
        logo: '/images/logo5.png',
        description: 'best Oreilly Marketer',
        rating: 4.3,
        numReviews: 68,
      },
    },
    {
      name: 'Thien Nguyen',
      email: 'thiennguyen@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Apple Iphone 13',
      category: 'Phones',
      image: '/images/p1.jpg',
      price: 999,
      countInStock: 28,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 8,
      description: 'beautiful iphone',
    },
    {
      name: 'Apple Macbook 2022',
      category: 'Laptops',
      image: '/images/p2.jpg',
      price: 1299,
      countInStock: 7,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 5,
      description: 'newest Apple laptop',
    },
    {
      name: 'Samsung Galaxy Note 2022',
      category: 'Phones',
      image: '/images/p3.jpg',
      price: 799,
      countInStock: 0,
      brand: 'Samsung',
      rating: 5.0,
      numReviews: 0,
      description: 'incoming - no product yet',
    },
    {
      name: 'Samsung Laptop 2022',
      category: 'Laptops',
      image: '/images/p4.jpg',
      price: 1199,
      countInStock: 15,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 14,
      description: 'newest Samsung laptop 2022',
    },
    {
      name: 'Google Pixel 2022',
      category: 'Phones',
      image: '/images/p5.jpg',
      price: 899,
      countInStock: 5,
      brand: 'Google',
      rating: 4.5,
      numReviews: 10,
      description: 'awesome Google Pixel up to now',
    },
    {
      name: 'Google Laptop 2022',
      category: 'Laptops',
      image: '/images/p6.jpg',
      price: 1349,
      countInStock: 12,
      brand: 'Google',
      rating: 4.7,
      numReviews: 12,
      description: 'high quality laptop from Google',
    },
    {
      name: 'Pearson TOEFL test',
      category: 'Books',
      image: '/images/p7.jpg',
      price: 59,
      countInStock: 49,
      brand: 'Pearson',
      rating: 4.7,
      numReviews: 18,
      description: 'the best book for Toefl practice',
    },
    {
      name: 'Oreilly Backend - Design Database',
      category: 'Books',
      image: '/images/p8.jpg',
      price: 79,
      countInStock: 28,
      brand: 'Oreilly',
      rating: 4.7,
      numReviews: 12,
      description: 'the best preparation for backend dev',
    },
  ],
};
export default data;
